# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kchen2 <kchen2@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/12 21:41:26 by kchen2            #+#    #+#              #
#    Updated: 2019/09/10 15:30:31 by kchen2           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#docker build -t ex00 .#
#docker run --rm -it ex00#


FROM alpine

RUN apk update && apk upgrade
RUN apk add vim

ENTRYPOINT vim